name: Feature Request
description: Request a feature
body:
- type: markdown
  attributes:
    value: |
      Thank you for taking the time to fill out this feature request.
- type: textarea
  id: feature-request
  attributes:
    label: Feature Request
    description: Please describe your feature request. The more detailed you can be, the better. You can upload any screenshots here as well (but please do not upload images of the mascot). Important: Please only use this Feature Request report for actual features; do not use this report to request to make it work with a specific website.
    placeholder: Describe your feature request
  validations:
    required: true
